config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :servers
  get 'settings', to: 'settings#index'
  put 'settings', to: 'settings#update'

  post 'dashboard/api_update', to: 'dashboard#api_update'

  root to: 'dashboard#index'
end

app/models/server.rb
class Server
  include Mongoid::Document
  include Mongoid::Timestamps

  field :node_id, type: Integer
  field :name, type: String
  field :host, type: String
  field :port, type: Integer
  field :password, type: String
  field :encryption_method, type: String
  field :timeout, type: Integer
  field :priority, type: Integer

  METHODS = ['rc4-md5', 'salsa20'].freeze

  validates :node_id, :name, :host, :port, :password, :encryption_method,
            :timeout, presence: true

  after_save :refresh_ss_config
  after_destroy :after_destroy

  scope :prioritize, -> { order(priority: :asc) }

  def self.active
    active_server_id = Setting.get('active_server_id')
    Server.find(active_server_id) unless active_server_id.nil?
  end

  def active?
    id.to_s == Setting.get('active_server_id')
  end

  def ss_config
    {
      server: host,
      server_port: port,
      local_address: '0.0.0.0',
      local_port: 1080,
      password: password,
      timeout: 60,
      method: encryption_method
    }.to_json
  end

  private

  def refresh_ss_config
    Setting.set('active_server_id', id) if active?
  end

  def after_destroy
    Setting.delete('active_server_id') if active?
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  def index
    @servers = Server.all
  end

  def show
  end

  def new
    @server = Server.new(default_attributes)
  end

  def edit
  end

  def create
    @server = Server.new(server_params)
    if @server.save
      redirect_to @server
    else
      render :new
    end
  end

  def update
    if @server.update(server_params)
      redirect_to @server, notice: 'Server was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @server.destroy
    redirect_to servers_path, notice: 'Server was successfully destroyed.'
  end

  private

  def default_attributes
    { timeout: 60, method: 'rc4-md5' }
  end

  def set_server
    @server = Server.find(params[:id])
  end

  def server_params
    params.require(:server).permit(
      :name, :host, :port, :password, :method, :timeout
    )
  end
end

app/views/servers/_form.html.erb
<%= simple_form_for @server do |f| %>
  <%= f.input :name %>
  <%= f.input :host %>
  <%= f.input :port, as: :integer %>
  <%= f.input :password %>
  <%= f.input :method, as: :select, collection: Server::METHODS %>
  <%= f.input :timeout, as: :integer, default: 60 %>
  <%= f.button :submit, value: t('servers.submit') %>
<% end %>

app/views/servers/edit.html.erb
<h1>Edit Server</h1>

<div class="row">
  <div class="medium-6 columns">
    <%= render 'form' %>
  </div>
</div>

app/views/servers/index.html.erb
<%= link_to 'Add server', new_server_path, class: 'button' %>

<table class='servers'>
  <thead>
    <tr>
      <th>Server</th>
      <th>Host</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @servers.each do |server| %>
    <% active_class = 'active' if server.active? %>
    <tr class="<%= active_class %>">
      <td><%= link_to server.name, server %></td>
      <td><%= server.host %></td>
      <td>
        <%= link_to 'Edit', edit_server_path(server) %>
        <%= link_to 'Delete', server, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Use', settings_path(data: { active_server_id: server.id }), method: :put unless server.active? %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/servers/new.html.erb
<h1><%= t('.add_server') %></h1>

<div class="row">
  <div class="medium-6 columns">
    <%= simple_form_for @server do |f| %>
      <%= f.input :name %>
      <%= f.input :host %>
      <%= f.input :port, as: :integer %>
      <%= f.input :password %>
      <%= f.input :method, as: :select, collection: Server::METHODS %>
      <%= f.input :timeout, as: :integer, default: 60 %>
      <%= f.button :submit, value: t('.add_server') %>
    <% end %>
  </div>
</div>

app/views/servers/show.html.erb
<%= link_to 'Back to Servers', servers_path, class: 'button' %>

<table>
  <thead>
    <tr>
      <th colspan="2"><%= @server.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Host</td>
      <td><%= @server.host %></td>
    </tr>
    <tr>
      <td>Port</td>
      <td><%= @server.port %></td>
    </tr>
    <tr>
      <td>Password</td>
      <td><%= @server.password %></td>
    </tr>
    <tr>
      <td>Method</td>
      <td><%= @server.method %></td>
    </tr>
    <tr>
      <td>Timeout</td>
      <td><%= @server.timeout %></td>
    </tr>
  </tbody>
</table>