config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :servers
  get 'settings', to: 'settings#index'
  put 'settings', to: 'settings#update'

  post 'dashboard/api_update', to: 'dashboard#api_update'

  root to: 'dashboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'Gateway Web' %></title>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
      <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="main-menu">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Gateway</li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><%= link_to 'Dashboard', root_path %></li>
          <li><%= link_to 'Servers', servers_path %></li>
          <li><%= link_to 'Settings', settings_path %></li>
        </ul>
      </div>
    </div>

    <main>
      <div class="row">
        <div class="small-12 columns">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>